TestRazorPages/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestRazorPages.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

TestRazorPages/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestRazorPages.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

TestRazorPages/Pages/Employees/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestRazorPages.Pages.Employees
{
 
    public class EditModel : PageModel
    {
        private IEmployeeRepository _employeeRepo;

        public EditModel(IEmployeeRepository employeeRepo)
        {
            _employeeRepo = employeeRepo;
        }

        [TempData]
        public string Message { get; set; }

        [BindProperty]
        public Employee Employee { get; set; }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            Employee = _employeeRepo.GetByID(id);

            if (Employee == null)
            {
                return RedirectToPage("Index");
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            Message = Employee.FirstName + " " + Employee.LastName + ", ID " + Employee.ID.ToString() + " would have been saved.";

            //return Page();
            return RedirectToPage("Index");
        }
    }
}

/*
Re: Radio Button in mvc get value
Jul 25, 2013 09:24 AM|LINK 
Give both radios the same name, but different value.
@using (Html.BeginForm())
{
  @Html.RadioButton("Gender", "male")
  @Html.RadioButton("Gender", "female")

  <input type="submit" value="Save" />
}
In your action, just take the radio name as a parameter
[HttpPost]
public ActionResult PostAction(string Gender)
{
  // do stuff with 'Gender' value
}

 */

TestRazorPages/Pages/Employees/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestRazorPages.Pages.Employees
{
    public class IndexModel : PageModel
    {
        public string Message { get; set; }

        private IEmployeeRepository _employeeRepo;
        public List<Employee> Employees { get; set; }

        public IndexModel(IEmployeeRepository userRepo)
        {
            _employeeRepo = userRepo;
        }

        public void OnGet()
        {
            Employees = _employeeRepo.GetAll();
        }
    }
}

TestRazorPages/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestRazorPages.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

TestRazorPages/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestRazorPages.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

TestRazorPages/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestRazorPages.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

TestRazorPages/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

TestRazorPages/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TestRazorPages/Pages/Employees/Add.cshtml
@page
@using TestRazorPages.Pages.Employees

@functions
{
[TempData]
public string Message { get; set; }

[BindProperty]
public Employee Employee { get; set; }

public async Task<IActionResult> OnPostJoinManagerAsync()
{
    if (!ModelState.IsValid)
    {
        return Page();
    }

    Message = Employee.FirstName + " " + Employee.LastName + " (ID " + Employee.ID.ToString() + ") would have been added as a Manager.";

    return Page();
    //return RedirectToPage("Index");
}

public async Task<IActionResult> OnPostJoinEmployeeAsync()
{
    if (!ModelState.IsValid)
    {
        return Page();
    }

    Message = Employee.FirstName + " " + Employee.LastName + " (ID " + Employee.ID.ToString() + ") would have been added as an Employee.";

    return Page();
    // return RedirectToPage("Index");
}
}


<h2>Add an Employee</h2>
<a asp-page="Index">Back to Employees</a>

<form method="post">
    <div>
        <div>
            <label asp-for="Employee.FirstName"></label>
            <input type="text" asp-for="Employee.FirstName" />
            <span asp-validation-for="Employee.FirstName"></span>
        </div>
        <div>
            <label asp-for="Employee.LastName"></label>
            <input type="text" asp-for="Employee.LastName" />
            <span asp-validation-for="Employee.LastName"></span>
        </div>
        <div>
            <label asp-for="Employee.DateOfBirth"></label>
            <input type="text" asp-for="Employee.DateOfBirth" />
            <span asp-validation-for="Employee.DateOfBirth"></span>
        </div>
        <div>
            <label asp-for="Employee.ID"></label>
            <input type="text" asp-for="Employee.ID" />
            <span asp-validation-for="Employee.ID"></span>
        </div>
    </div>
    <div>
        <input type="submit" value="Add as Manager" asp-page-handler="JoinManager" />
        <input type="submit" value="Add as Employee" asp-page-handler="JoinEmployee" />
    </div>
    @Model.Message;
</form>

TestRazorPages/Pages/Employees/Edit.cshtml
@page "{id:int}"

@model TestRazorPages.Pages.Employees.EditModel

<h2>Edit an Employee</h2>
<a asp-page="Index">Back to Employees</a>

<form method="post">
    <div>
        <div>
            <label asp-for="Employee.FirstName"></label>
            <input type="text" asp-for="Employee.FirstName" />
            <span asp-validation-for="Employee.FirstName"></span>
        </div>
        <div>
            <label asp-for="Employee.LastName"></label>
            <input type="text" asp-for="Employee.LastName" />
            <span asp-validation-for="Employee.LastName"></span>
        </div>
        <div>
            <label asp-for="Employee.DateOfBirth"></label>
            <input type="text" asp-for="Employee.DateOfBirth" />
            <span asp-validation-for="Employee.DateOfBirth"></span>
        </div>
        <div>



        </div>
        <div>
            <label asp-for="Employee.ID"></label>
            <input type="text" asp-for="Employee.ID" />
            <span asp-validation-for="Employee.ID"></span>
        </div>
    </div>
    <div>
        <input type="submit" value="Submit" />
    </div>
    <h3>@Model.Message</h3>
</form>

TestRazorPages/Pages/Employees/Index.cshtml
@page
@using TestRazorPages.Pages.Employees

@model IndexModel


<h2>Employees</h2>

<a asp-page="Add">Add an Employee</a>

<h3>@Model.Message</h3>

<table>
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Date of Birth
            </th>
            <th>
                Gender
            </th>
            <th>
                Employee ID
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var employee in Model.Employees)
        {
        <tr>
            <td>
                @(employee.FirstName + " " + employee.LastName)
            </td>
            <td>
                @employee.DateOfBirth.ToShortDateString()
            </td>
            <td>
                @employee.Gender.ToString()
            </td>
            <td>
                @employee.ID
            </td>
            <td>
                <a asp-page="Edit" asp-route-id="@employee.ID">Edit</a>
            </td>
        </tr>
        }
    </tbody>
</table>

TestRazorPages/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<h2>MQ's Turorial Projects</h2>
<br /><br />I created this project to learn Razor PAges. <br />

<h2>ASP.NET Core Demystified - Razor Pages, Mathew Jones</h2><br/>
<a href="https://exceptionnotfound.net/asp-net-core-demystified-razor-pages/">Great Razor Pages Tutorial</a>
<br />
<h2>Using Dapper Asynchronously in ASP.NET Core 2.1</h2>
Figured out how to implement the <strong>IEmployeeRepository</strong> from this one, Also by Mathew Jones<br />
                                                                                                         <a href="https://exceptionnotfound.net/using-dapper-asynchronously-in-asp-net-core-2-1/">Using Dapper Asynchronously in ASP.NET Core 2.1</a><br />


<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core Razor Pages</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?linkid=852130">Working with Razor Pages.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure App Service</a></li>
        </ul>
    </div>
</div>

TestRazorPages/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestRazorPages</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">TestRazorPages</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Employees/Index">Employees</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - TestRazorPages</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>